name: Release
on:
  push:
    branches:
      - main  # or your default branch
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Get version
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build application
        run: npm run build

      - name: Package application
        run: npm run package

      - name: Update or create release tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f release
          git push origin :refs/tags/release
          git push origin release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release
          release_name: Release ${{ steps.package_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/Streamflix Setup ${{ steps.package_version.outputs.version }}.exe
          asset_name: Streamflix-Setup-${{ steps.package_version.outputs.version }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload latest.yml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/latest.yml
          asset_name: latest.yml
          asset_content_type: application/yaml